# -*- coding: utf-8 -*-
"""app

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sqEEiHivFOPX7uWwXkLo2SrETz4n0q5T
"""

import streamlit as st
import pickle
import numpy as np

# ===== Load model & tools =====
@st.cache_resource
def load_all():
    with open("model.pkl", "rb") as f:
        model = pickle.load(f)
    with open("tfidf.pkl", "rb") as f:
        tfidf = pickle.load(f)
    with open("label_encoder.pkl", "rb") as f:
        label_encoder = pickle.load(f)
    with open("severity_ohe.pkl", "rb") as f:
        severity_ohe = pickle.load(f)
    return model, tfidf, label_encoder, severity_ohe

model, tfidf, label_encoder, severity_ohe = load_all()

# ===== UI =====
st.title("🧠 Eye Disease Classification")
st.write("Masukkan deskripsi gejala mata")

text_input = st.text_area("Gejala Mata")

if st.button("Predict"):
    if text_input.strip() == "":
        st.warning("Input tidak boleh kosong")
    else:
        # TF-IDF transform
        X = tfidf.transform([text_input])

        # Predict
        pred = model.predict(X)
        label = label_encoder.inverse_transform(pred)[0]

        st.success(f"Diagnosis: **{label}**")